### PR TITLE
Update inputs to use updated topography around Antarctica.

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
Contributes to https://github.com/COSIMA/access-om2/issues/265

### CODE REVIEW

**Comment by aekiss** [comment]
@micaeljtoliveira is this ready to merge? @aidanheerdegen's team is waiting on it for their release https://github.com/ACCESS-NRI/access-om2-configs/issues/17#issuecomment-1968012588, and Wilma found it worked fine in CM2-025 https://github.com/COSIMA/access-om2/issues/265#issuecomment-1832927619

**Comment by aidanheerdegen** [comment]
We're also going to be held up by the [grid issues with the 0.25 model](https://github.com/COSIMA/access-om2/issues/280), but yes it would be good to get this merged if it is fixed now.

**Comment by micaeljtoliveira** [comment]
@aekiss All good from my side to merge this.

**Comment by aekiss** [comment]
OK, merged (skipped CI - Jenkins RIP)

**Pull request merged**
